### PR TITLE
fix ticket description selectors

### PR DESCRIPTION
**Pull request by incompl**
Ticket descriptions on current TXJS site are broken due to my fragile selectors. This PR is a quick fix. Ideas on a better way are welcome!

Attention @ajpiano @SlexAxton

### CODE REVIEW

**Comment by incompl** [comment]
@SlexAxton @ajpiano Can you deploy this?

**Comment by ajpiano** [comment]
I can't but @SlexAxton can

**Comment by incompl** [comment]
Ping @SlexAxton ^^

**Comment by SlexAxton** [comment]
Sorry, was away from home, this is deployed

**Comment by incompl** [comment]
Thank you so much!

**Pull request merged**
