### PR TITLE
Roost section and Tito widget subtitles

### PR DESCRIPTION
**Pull request by incompl**
screen shot 2015-04-28 at 11 18 25 am

### CODE REVIEW

**Comment by SlexAxton** [comment]
Two maybes:
- I'd personally switch "roost" and "preconference training event" - it makes it seem more official.
- While you're in here, can you switch "buy tickets early" to just "buy tickets"?

**Comment by SlexAxton** [comment]
Cc @ajpiano

**Comment by incompl** [comment]
@SlexAxton Like this?

screen shot 2015-04-28 at 1 45 06 pm

**Comment by SlexAxton** [comment]
Yep. I can deploy this in an hour two if you folks are happy with it.

**Comment by incompl** [comment]
Updated the PR, good to merge! @SlexAxton @ajpiano

**Comment by ajpiano** [comment]
Looks good to me, though GitHub is fretting about a potential merge conflict. We'll have a new logo to add soon but that can be a separate PR

**Comment by incompl** [comment]
@SlexAxton @ajpiano fixed the merge conflict, this is ready to go!

**Pull request merged**
